language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8
  - coverage run --source='.' manage.py test
  - coverage report

after_success:
  - coveralls


deploy:
  - provider: elasticbeanstalk
    region: "us-west-2"
    app: "bam-prod"
    env: "bam-env"
    bucket_name: "elasticbeanstalk-us-west-2-906796636311"
    bucket_path: "bam-prod"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
      branch: develop
