language: python

python:
  - 3.7

install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry install -vvv

before_script:
  - poetry run python manage.py migrate
  - poetry run python manage.py collectstatic --noinput

script:
  - poetry run black --check .
  - poetry run flake8
  - poetry run coverage run --source='.' manage.py test
  - poetry run coverage report

after_success:
  - poetry run coveralls

before_deploy:
  - poetry export -f requirements.txt --output requirements.txt
  - git config --global user.email "NA"
  - git config --global user.name "NA"
  - git add -f db.sqlite3 static/ requirements.txt
  - git commit -m "Surpassing Travis EB incompatibility"

deploy:
  provider: script
  script: |
    echo "Deploying to AWS Elastic Beanstalk..."
    sudo apt-get install tree
    ls -la
    tree -I "__pycache__|static"
  on:
    branch: clean-repo
