language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8
  - coverage run --source='.' manage.py test
  - coverage report

after_success:
  - coveralls


deploy:
  - provider: elasticbeanstalk
    region: $AWS_REGION
    app: $AWS_APP
    env: $AWS_ENV
    bucket_name: $AWS_BUCKET_NAME
    bucket_path: $AWS_BUCKET_PATH
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
      branch:
        - main
        - develop
